### ISSUE TITLE
A bunch of tests fail out of the box

### ISSUE THREAD

**Issue by norswap** [Jeiwan/zuniswapv2#1]
Pulling from `master` and running according to instructions, the output from `forge test -vv` is:

Using forge 0.2.0 (5279f69 2022-06-29T00:03:58.834625889Z)
Using solc 0.8.13

```
[⠢] Compiling...
No files changed, compilation skipped

Running 4 tests for src/test/ZuniswapV2Factory.t.sol:ZuniswapV2FactoryTest
[PASS] testCreatePair() (gas: 1708029)
[PASS] testCreatePairIdenticalTokens() (gas: 13742)
[PASS] testCreatePairPairExists() (gas: 1713507)
[PASS] testCreatePairZeroAddress() (gas: 18542)
Test result: ok. 4 passed; 0 failed; finished in 14.30ms

Running 17 tests for src/test/ZuniswapV2Library.t.sol:ZuniswapV2LibraryTest
[PASS] testGetAmountIn() (gas: 4111)
[PASS] testGetAmountInZeroInputAmount() (gas: 9362)
[PASS] testGetAmountInZeroInputReserve() (gas: 9381)
[PASS] testGetAmountInZeroOutputReserve() (gas: 9388)
[PASS] testGetAmountOut() (gas: 3947)
[PASS] testGetAmountOutZeroInputAmount() (gas: 9265)
[PASS] testGetAmountOutZeroInputReserve() (gas: 9271)
[PASS] testGetAmountOutZeroOutputReserve() (gas: 9367)
[FAIL. Reason: Revert] testGetAmountsIn() (gas: 576611)
[PASS] testGetAmountsInInvalidPath() (gas: 14934)
[FAIL. Reason: Revert] testGetAmountsOut() (gas: 576678)
[PASS] testGetAmountsOutInvalidPath() (gas: 15088)
[FAIL. Reason: Revert] testGetReserves() (gas: 203882)
[FAIL] testPairFor() (gas: 24168)
Logs:
  Error: a == b not satisfied [address]
    Expected: 0x7ee0d4680a40bf8035e41d7d3dd2b89b8fe043eb
      Actual: 0x7dedb0778f3632828e120773699d68ff2cd0b882

[PASS] testPairForNonexistentFactory() (gas: 5213)
[FAIL] testPairForTokensSorting() (gas: 24134)
Logs:
  Error: a == b not satisfied [address]
    Expected: 0x7ee0d4680a40bf8035e41d7d3dd2b89b8fe043eb
      Actual: 0x7dedb0778f3632828e120773699d68ff2cd0b882

[PASS] testQuote() (gas: 5847)
Test result: FAILED. 12 passed; 5 failed; finished in 17.58ms

Running 12 tests for src/test/ZuniswapV2Router.t.sol:ZuniswapV2RouterTest
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalIsOk() (gas: 1956584)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalIsTooHighAmountAOk() (gas: 1957367)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalIsTooLow() (gas: 1963136)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalTooHighAmountATooLow() (gas: 1963180)
[FAIL. Reason: Revert] testAddLiquidityCreatesPair() (gas: 1775581)
[FAIL. Reason: Revert] testAddLiquidityNoPair() (gas: 1775622)
[FAIL. Reason: Revert] testRemoveLiquidity() (gas: 1775604)
[FAIL. Reason: Revert] testRemoveLiquidityInsufficientAAmount() (gas: 1775582)
[FAIL. Reason: Revert] testRemoveLiquidityInsufficientBAmount() (gas: 1775583)
[FAIL. Reason: Revert] testRemoveLiquidityPartially() (gas: 1775605)
[FAIL. Reason: Revert] testSwapExactTokensForTokens() (gas: 1805362)
[FAIL. Reason: Revert] testSwapTokensForExactTokens() (gas: 1805361)
Test result: FAILED. 0 passed; 12 failed; finished in 17.96ms

Running 21 tests for src/test/ZuniswapV2Pair.t.sol:ZuniswapV2PairTest
[PASS] testBurn() (gas: 208218)
[PASS] testBurnUnbalanced() (gas: 225865)
[PASS] testBurnUnbalancedDifferentUsers() (gas: 282096)
[PASS] testBurnZeroLiquidity() (gas: 206801)
[PASS] testBurnZeroTotalSupply() (gas: 31216)
[PASS] testCumulativePrices() (gas: 336666)
[PASS] testFlashloan() (gas: 489533)
[PASS] testMintBootstrap() (gas: 198283)
[PASS] testMintLiquidityUnderflow() (gas: 31425)
[PASS] testMintUnbalanced() (gas: 217888)
[PASS] testMintWhenTheresLiquidity() (gas: 266169)
[PASS] testMintZeroLiquidity() (gas: 139368)
[FAIL] testReservesPacking() (gas: 208736)
Logs:
  Error: a == b not satisfied [bytes32]
    Expected: 0x000000000000000000001bc16d674ec800000000000000000de0b6b3a7640000
      Actual: 0x000000010000000000001bc16d674ec800000000000000000de0b6b3a7640000

[PASS] testSwapBasicScenario() (gas: 218598)
[PASS] testSwapBasicScenarioReverseDirection() (gas: 218384)
[PASS] testSwapBidirectional() (gas: 226409)
[PASS] testSwapInsufficientLiquidity() (gas: 249592)
[PASS] testSwapOverpriced() (gas: 239887)
[PASS] testSwapUnderpriced() (gas: 218489)
[PASS] testSwapUnpaidFee() (gas: 235974)
[PASS] testSwapZeroOut() (gas: 224110)
Test result: FAILED. 20 passed; 1 failed; finished in 19.09ms

Failed tests:
[FAIL. Reason: Revert] testGetAmountsIn() (gas: 576611)
[FAIL. Reason: Revert] testGetAmountsOut() (gas: 576678)
[FAIL. Reason: Revert] testGetReserves() (gas: 203882)
[FAIL] testPairFor() (gas: 24168)
[FAIL] testPairForTokensSorting() (gas: 24134)
[FAIL] testReservesPacking() (gas: 208736)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalIsOk() (gas: 1956584)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalIsTooHighAmountAOk() (gas: 1957367)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalIsTooLow() (gas: 1963136)
[FAIL. Reason: Revert] testAddLiquidityAmountBOptimalTooHighAmountATooLow() (gas: 1963180)
[FAIL. Reason: Revert] testAddLiquidityCreatesPair() (gas: 1775581)
[FAIL. Reason: Revert] testAddLiquidityNoPair() (gas: 1775622)
[FAIL. Reason: Revert] testRemoveLiquidity() (gas: 1775604)
[FAIL. Reason: Revert] testRemoveLiquidityInsufficientAAmount() (gas: 1775582)
[FAIL. Reason: Revert] testRemoveLiquidityInsufficientBAmount() (gas: 1775583)
[FAIL. Reason: Revert] testRemoveLiquidityPartially() (gas: 1775605)
[FAIL. Reason: Revert] testSwapExactTokensForTokens() (gas: 1805362)
[FAIL. Reason: Revert] testSwapTokensForExactTokens() (gas: 1805361)

Encountered a total of 18 failing tests, 36 tests succeeded
```

**Comment by norswap** [comment]
Okay, I've solved all of them!

In `ZuniswapV2Library.sol`, updating the hash of the init code to `hex"3b5e0380fb57aae32ca00f5843c987b8e66faba514a6cf83af255f5a419d7b41"` (proper value for solc 0.8.13) fixes a lot of the issues.

Ideally, this value should be read directly from the build outputs, and injected somewhere (presumably in `ZuniswapV2Factory`). In test, I think there is now a foundry cheat code to read from disk?

The constant in `tesPairForNonExistantFactory` can similarly be updated to `0x93410288511F149c7e3F3FC9Ce3A8B7353eeCA44`, and in `testAddLiquidityCreatesPair` to `0x4d88e1ECd6e23390771A6Fb204D4ae0444CbF831`

For the `testReservesPacking()` test, the issue seems the be the assumption that the timestamp, which is packed into the same storage slot is zero, but it's actually 1 now. Fixed by replacing the hardcoded string with:

```
bytes32(abi.encodePacked(
                uint32(block.timestamp),     // blockTimestampLast
                uint112(0x1BC16D674EC80000), // 2 * 10^18 (token1 balance)
                uint112(0xDE0B6B3A7640000))) // 1 * 10^18 (token 0 balance)
```

I'll try to make a PR later when I have a bit more time.

**Comment by Jeiwan** [comment]
Thanks for reporting!

This is an educational project, it's not expected to be deployed and run anywhere except a local network. It's also not expected to receive any changes that are not covered in the related blog posts to not confuse readers.

**Comment by norswap** [comment]
Hey! I appreciate the answer.

> This is an educational project, it's not expected to be deployed and run anywhere except a local network. 

Currently, not everything in the project can be run correctly on a local network when using a different Solidity version than you used (in particular, everything that uses `pairFor` in the periphery library, including parts of the router, won't work).

And the test don't pass, of course.

I think at the very least, the used solidity version should be documented and added in a `foundry.toml` file (and we should check that this actually works, I'm not even sure it suffices).

It seems to me that you value the learning experience a great deal. How can the user be confident he's learning something correct or still relevant when he tries to run the test and a third of them fail?

> It's also not expected to receive any changes that are not covered in the related blog posts to not confuse readers.

A solution there would be to edit the various branches so that they work with a recent solidity.

Another one would be to isolate the changes needed to run under a recent Solidity version in their own branch, and link to that branch from the README.md. That should avoid confusing users.

**Comment by Jeiwan** [comment]
@norswap Makes sense! I'll lock a specific Foundry/Solidity version in the project and port it to all the branches.
Thanks for contributing!

**Comment by joedakwa** [comment]
> Hey! I appreciate the answer.
> 
> > This is an educational project, it's not expected to be deployed and run anywhere except a local network.
> 
> Currently, not everything in the project can be run correctly on a local network when using a different Solidity version than you used (in particular, everything that uses `pairFor` in the periphery library, including parts of the router, won't work).
> 
> And the test don't pass, of course.
> 
> I think at the very least, the used solidity version should be documented and added in a `foundry.toml` file (and we should check that this actually works, I'm not even sure it suffices).
> 
> It seems to me that you value the learning experience a great deal. How can the user be confident he's learning something correct or still relevant when he tries to run the test and a third of them fail?
> 
> > It's also not expected to receive any changes that are not covered in the related blog posts to not confuse readers.
> 
> A solution there would be to edit the various branches so that they work with a recent solidity.
> 
> Another one would be to isolate the changes needed to run under a recent Solidity version in their own branch, and link to that branch from the README.md. That should avoid confusing users.

Hey, @norswap & @Jeiwan if i wanted to clone this repo, which branch is best? I was having similar issues with failing tests in the Router.t.sol, but everything else seemed to work? Thanks
